(()=>{const K='chrisV2',DB='chrisV2Photos',STORE='photos',ANGLES=['front','left','right','back'],MS=864e5;const P={A:{t:'SESSION A — CHEST / SHOULDERS / LEGS / CORE',e:[['push','Push-ups / incline push-ups','8–12','Use a counter/desk if floor reps are not clean.'],['pike','Pike push-ups','6–10','Hips high, controlled range.'],['squat','Slow squats','12–15','About 3 sec down.'],['dead','Dead bugs','8 / side','Slow; back stays controlled.'],['plank','Plank','20–30 sec','Brace and breathe.']]},B:{t:'SESSION B — LEGS / GLUTES / BACK / WAIST',e:[['lunge','Reverse lunges','8 / leg','Hold support if needed.'],['bridge','Glute bridges','12–15','Squeeze glutes at top.'],['ytw','Prone Y-T-W','6 each','Small controlled lifts.'],['bird','Bird dogs','8 / side','Keep hips square.'],['side','Side plank','15–20 sec / side','Bent-knee is fine.']]},C:{t:'SESSION C — FULL BODY',e:[['pushc','Push-ups / incline push-ups','8–12','Same level as Monday.'],['split','Split squats','8 / leg','Tall posture, controlled.'],['pikec','Pike push-ups','6–10','Controlled shoulder work.'],['angel','Reverse snow angels','10–12','Slow sweep.'],['mount','Slow mountain climbers','10 / side','No bouncing.'],['plankc','Plank','20–30 sec','Brace and breathe.']]}};const phases=[[1,2,2,'2 rounds · 45 sec between exercises · 90 sec between rounds'],[3,4,3,'3 rounds · add reps before difficulty'],[5,7,3,'3 rounds · slow 3-sec lowering on main moves'],[8,8,2,'2 rounds · deload'],[9,11,3,'3 rounds · stronger versions where earned'],[12,12,3,'3 rounds · benchmark clean reps']];let st=load(),db,active,pending;function def(){return{settings:{start:'2026-08-10',base:84.3},workouts:{},metrics:[{id:'base',date:'2026-08-07',week:0,weight:84.3,waist:null,bf:null,muscle:null,notes:'Baseline'}]}}
function load(){try{let x=JSON.parse(localStorage.getItem(K)||'{}');return Object.assign(def(),x,{settings:Object.assign(def().settings,x.settings||{})})}catch(e){return def()}}
function save(){localStorage.setItem(K,JSON.stringify(st));render()}
function q(x){return document.getElementById(x)}
function ld(d=new Date){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function pd(s){let a=s.split('-').map(Number);return new Date(a[0],a[1]-1,a[2],12)}
function diff(a,b){return Math.floor((pd(a)-pd(b))/MS)}
function wk(s){let d=diff(s,st.settings.start);return d<0?0:Math.floor(d/7)+1}
function ses(s){let d=diff(s,st.settings.start);if(d<0||d>=84)return null;return ['A',null,'B',null,'C',null,null][d%7]}
function roundCount(w){let p=phases.find(x=>w>=x[0]&&w<=x[1]);return p?p[2]:2}
function phaseText(w){let p=phases.find(x=>w>=x[0]&&w<=x[1]);return p?p[3]:''}
function fmt(s){return pd(s).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}
function latest(k){return st.metrics.filter(x=>x[k]!=null).sort((a,b)=>a.date.localeCompare(b.date)).at(-1)}
function first(k){return st.metrics.filter(x=>x[k]!=null).sort((a,b)=>a.date.localeCompare(b.date))[0]}
function toast(s){q('toast').textContent=s;q('toast').classList.add('on');setTimeout(()=>q('toast').classList.remove('on'),1700)}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x.dataset.p===id));scrollTo(0,0);if(id==='photos'){renderPhotos();renderCompare()}}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.p));setInterval(()=>{let d=new Date();q('clock').textContent=d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});q('date').textContent=d.toLocaleDateString('en-GB',{weekday:'long',day:'2-digit',month:'long'}).toUpperCase()},1000);function fill(id){let s=q(id),v=s.value;s.innerHTML='';for(let i=0;i<=12;i++)s.innerHTML+=`<option value="${i}">${i?'Week '+i:'Week 0 — Baseline'}</option>`;if(v)s.value=v}['mweek','pweek','ca','cb'].forEach(fill);q('ca').value=0;q('cb').value=12;function programs(){q('programs').innerHTML=Object.values(P).map(p=>`<div class="card sesCard"><h3>${p.t}</h3><div class="focus">WEEK 1: 2 ROUNDS</div><table>${p.e.map((x,i)=>`<tr><td><b>${i+1}. ${x[1]}</b><span class="cue">${x[3]}</span></td><td>${x[2]}</td></tr>`).join('')}</table><div class="note">Do all once = 1 round. Rest ~90 sec, repeat from exercise 1.</div></div>`).join('')}
function due(){let t=pd(ld()),n=0;for(let i=0;i<84;i++){let d=new Date(pd(st.settings.start).getTime()+i*MS);if(d>t)break;if([0,2,4].includes(i%7))n++}return n}
function render(){let w=Math.min(12,wk(ld())),done=Object.values(st.workouts).filter(x=>x.complete).length,weight=latest('weight')?.weight??st.settings.base;q('bar').style.width=Math.min(100,done/36*100)+'%';q('barText').textContent=done+' / 36 sessions complete';q('weekText').textContent=w?'WEEK '+w:'PREP WEEK';q('cw').textContent=(+weight).toFixed(1);q('wk').textContent=w;q('sd').textContent=done;q('ci').textContent=new Set(st.metrics.filter(x=>x.week>0).map(x=>x.week)).size;renderToday();renderWeek();renderHistory();programs();q('start').value=st.settings.start;q('base').value=st.settings.base}
function step(n,a,b,c){q('steps').innerHTML+=`<div class="step"><div class="num">${n}</div><div><b>${a}</b><p>${b}</p></div><span>${c}</span></div>`}
function renderToday(){let d=ld(),w=wk(d),s=ses(d),dow=pd(d).getDay();q('steps').innerHTML='';q('todayActions').innerHTML='';if(w===0){q('badge').textContent='PREP WEEK';q('todayTitle').textContent='Baseline only';q('todayText').textContent='Monday is workout one. Today just set the tracker up.';step(1,'Log weight + waist','Use Check-ins.','5 MIN');step(2,'Upload 4 photos','Front, left, right, back.','5 MIN');step(3,'Stop','No bonus workout.','DONE');q('todayActions').innerHTML='<button class="primary" id="planBtn">SEE MONDAY PLAN</button>';q('planBtn').onclick=()=>show('plan');return}if(s){let p=P[s],r=roundCount(w);q('badge').textContent='WEEK '+w+' // '+s;q('todayTitle').textContent=p.t;q('todayText').textContent='Warm up, then '+r+' rounds. 45 sec between exercises, 90 sec between rounds.';step(1,'Warm-up','60 sec march · arm circles · 8 squat+reach · 10 hip hinges · 5 easy push-ups','5 MIN');p.e.forEach((x,i)=>step(i+2,x[1],x[3],x[2]));step(p.e.length+2,'Repeat whole list','Complete '+r+' total rounds.',''+r+' ROUNDS');step(p.e.length+3,'Finished','Save workout and get on with your day.','STOP');q('todayActions').innerHTML='<button class="primary" id="startBtn">START WORKOUT</button>';q('startBtn').onclick=()=>openWorkout(d);return}if(dow===0){q('badge').textContent='WEEK '+w+' // CHECK-IN';q('todayTitle').textContent='Sunday check-in';q('todayText').textContent='Ten minutes, then ignore the numbers for another week.';step(1,'Weigh','Same conditions if possible.','1 MIN');step(2,'Waist','At navel, relaxed.','2 MIN');step(3,'Photos','Front, left, right, back.','5 MIN');step(4,'One note','Energy, fit, soreness, wins.','2 MIN');q('todayActions').innerHTML='<button class="primary" id="logBtn">OPEN CHECK-IN</button>';q('logBtn').onclick=()=>show('log');return}let run=dow===2||dow===6;q('badge').textContent='WEEK '+w+' // '+(run?'OPTIONAL RUN':'RECOVERY');q('todayTitle').textContent=run?'Easy day':'Recovery day';q('todayText').textContent=run?'Normal walking plus an optional 1–2 km easy jog if you fancy it.':'No formal workout. Normal walking is enough.';step(1,'Normal walking','Commute + lunch + normal life.','COUNTS');if(run)step(2,'Optional jog','1–2 km conversational pace. Skip if sore.','OPTIONAL');step(run?3:2,'Recover','Food, hydration, sleep.','DONE')}
function renderWeek(){let el=q('week');el.innerHTML='';let w=Math.max(1,Math.min(12,wk(ld()))),start=new Date(pd(st.settings.start).getTime()+(w-1)*7*MS);for(let i=0;i<7;i++){let d=new Date(start.getTime()+i*MS),ds=ld(d),s=ses(ds),type=s?'SESSION '+s:(i===1||i===5?'OPTIONAL 1–2KM':i===6?'CHECK-IN':'RECOVERY'),x=document.createElement('div');x.className='day '+(ds===ld()?'today ':'')+(st.workouts[ds]?.complete?'done':'');x.innerHTML=`<div class="d1">${d.toLocaleDateString('en-GB',{weekday:'short'}).toUpperCase()}</div><div class="d2">${d.getDate()}</div><div class="d3">${type}</div>`;if(s)x.onclick=()=>openWorkout(ds);el.appendChild(x)}}
function openWorkout(date){let s=ses(date),w=wk(date),rN=roundCount(w),p=P[s],log=st.workouts[date]||{},html='';active={date,s};q('dh').textContent=fmt(date)+' // '+p.t;q('modalNote').textContent=rN+' rounds today. '+phaseText(w);for(let r=1;r<=rN;r++){let old=log.rounds?.[r]||{};if(r===1&&log.e&&!log.rounds)old=log.e;html+=`<div class="round"><div class="rh"><b>ROUND ${r} OF ${rN}</b><span>ALL EXERCISES ONCE</span></div>${p.e.map(x=>`<div class="row"><input type="checkbox" data-r="${r}" data-e="${x[0]}" ${old[x[0]]?'checked':''}><div><b>${x[1]}</b><p>${x[3]}</p></div><span>${x[2]}</span></div>`).join('')}</div>`}q('rounds').innerHTML=html;q('dlg').showModal()}
function saveWorkout(all){let rounds={};document.querySelectorAll('#rounds [data-e]').forEach(x=>{if(all)x.checked=true;rounds[x.dataset.r]=rounds[x.dataset.r]||{};rounds[x.dataset.r][x.dataset.e]=x.checked});let complete=[...document.querySelectorAll('#rounds [data-e]')].every(x=>x.checked);st.workouts[active.date]={s:active.s,rounds,complete};save();q('dlg').close();toast(complete?'Workout complete. Banked.':'Workout saved.')}q('close').onclick=()=>q('dlg').close();q('saveWorkout').onclick=()=>saveWorkout(false);q('finishWorkout').onclick=()=>saveWorkout(true);q('mdate').value=ld();q('mweek').value=Math.min(12,wk(ld()));q('form').onsubmit=e=>{e.preventDefault();let rec={id:'m'+Date.now(),date:q('mdate').value,week:+q('mweek').value,weight:q('weight').value?+q('weight').value:null,waist:q('waist').value?+q('waist').value:null,bf:q('bf').value?+q('bf').value:null,muscle:q('muscle').value?+q('muscle').value:null,notes:q('notes').value};st.metrics.push(rec);save();e.target.reset();q('mdate').value=ld();q('mweek').value=Math.min(12,wk(ld()));toast('Check-in saved.')}
function v(x,u=''){return x==null?'—':(+x).toFixed(1)+u}
function esc(s){return String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function renderHistory(){q('hist').innerHTML=[...st.metrics].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${fmt(x.date)}</td><td>${x.week}</td><td>${v(x.weight,' kg')}</td><td>${v(x.waist,' cm')}</td><td>${v(x.bf,'%')}</td><td>${v(x.muscle,' kg')}</td><td>${esc(x.notes)}</td><td>${x.id==='base'?'':`<button class="danger" data-del="${x.id}">X</button>`}</td></tr>`).join('');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{st.metrics=st.metrics.filter(x=>x.id!==b.dataset.del);save()})}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function get(k){return new Promise((res,rej)=>{let r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(k,v){return new Promise((res,rej)=>{let t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(v,k);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function del(k){return new Promise(res=>{let t=db.transaction(STORE,'readwrite');t.objectStore(STORE).delete(k);t.oncomplete=res})}
function compress(f){return new Promise((res,rej)=>{let i=new Image(),u=URL.createObjectURL(f);i.onload=()=>{let sc=Math.min(1,1000/i.width),c=document.createElement('canvas');c.width=i.width*sc;c.height=i.height*sc;c.getContext('2d').drawImage(i,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(u);res(b)},'image/jpeg',.76)};i.onerror=rej;i.src=u})}async function renderPhotos(){let w=+q('pweek').value,g=q('photoGrid');g.innerHTML='';for(let a of ANGLES){let b=await get(w+'-'+a),d=document.createElement('div');d.className='photo';d.innerHTML=`<div class="ang">${a.toUpperCase()}</div><div class="empty">WEEK ${w}<br>${a.toUpperCase()}</div><div class="ops"><button data-up="${a}">UPLOAD</button><button data-x="${a}">DELETE</button></div>`;if(b){let i=document.createElement('img');i.src=URL.createObjectURL(b);d.prepend(i)}g.appendChild(d)}document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{pending={w,a:b.dataset.up};q('photoInput').click()});document.querySelectorAll('[data-x]').forEach(b=>b.onclick=async()=>{await del(w+'-'+b.dataset.x);renderPhotos();renderCompare()})}q('photoInput').onchange=async e=>{if(e.target.files[0]&&pending){await put(pending.w+'-'+pending.a,await compress(e.target.files[0]));e.target.value='';renderPhotos();renderCompare();toast('Photo saved.')}};q('pweek').onchange=renderPhotos;q('ca').onchange=renderCompare;q('cb').onchange=renderCompare;async function renderCompare(){let g=q('compare');g.innerHTML='';for(let w of [+q('ca').value,+q('cb').value]){let c=document.createElement('div');c.className='card comp';c.innerHTML=`<h4>WEEK ${w}</h4><div class="pics"></div>`;for(let a of ANGLES){let b=await get(w+'-'+a),i=document.createElement('img');if(b)i.src=URL.createObjectURL(b);c.querySelector('.pics').appendChild(i)}g.appendChild(c)}}
function allPhotos(){return new Promise((res,rej)=>{let o={},r=db.transaction(STORE).objectStore(STORE).openCursor();r.onsuccess=e=>{let c=e.target.result;if(c){o[c.key]=c.value;c.continue()}else res(o)};r.onerror=()=>rej(r.error)})}
function b64(b){return new Promise(res=>{let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(b)})}
function blob(s){let a=s.split(','),m=a[0].match(/:(.*?);/)[1],x=atob(a[1]),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return new Blob([u],{type:m})}q('export').onclick=async()=>{let p=await allPhotos(),o={state:st,photos:{}};for(let k in p)o.photos[k]=await b64(p[k]);let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o)]));a.download='chris-v2-backup-'+ld()+'.json';a.click()};q('import').onchange=async e=>{let o=JSON.parse(await e.target.files[0].text());st=o.state;localStorage.setItem(K,JSON.stringify(st));for(let k in(o.photos||{}))await put(k,blob(o.photos[k]));render();renderPhotos();renderCompare();toast('Backup restored.')};q('saveSettings').onclick=()=>{st.settings.start=q('start').value||'2026-08-10';st.settings.base=+q('base').value||84.3;save();toast('Settings saved.')};q('reset').onclick=()=>{if(confirm('Delete all tracker data and photos on this device?')){localStorage.removeItem(K);st=def();let t=db.transaction(STORE,'readwrite');t.objectStore(STORE).clear();t.oncomplete=()=>{render();renderPhotos();renderCompare()}}};(async()=>{db=await openDB();render();renderPhotos();renderCompare()})()})();